name: Update README with Wakatime coding stats

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '00 7 * * *'

jobs:
  update-Readme:
    name: README Coding stats updater   
    runs-on: ubuntu-latest
    steps:
      - uses: tariksahni/coding-stats-wakatime@v1.0.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_MONTHLY: true
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_ACTION: ${{ github.action }}
